language: ruby
matrix:
  include:
    - rvm: 1.9.3
      env: PUPPET_VERSION=2.7.26
      gemfile: Gemfile
    - rvm: 1.9.3
      env: PUPPET_VERSION=3.7.5
      gemfile: Gemfile
    - rvm: 2.2.0
      env: PUPPET_VERSION=4.2.3 STRICT_VARIABLES="no"
      gemfile: Gemfile
script:
  - "bundle exec rake validate"
  - "bundle exec rake lint"
  - "bundle exec rake spec"
notifications:
  email:
    on_failure: always
sudo: false
